
GET http://127.0.0.1:8000/hello/2021



###
GET http://127.0.0.1:8000/measures/



###
POST http://127.0.0.1:8000/users/
Content-Type: application/json

{
    "name": "Mario",
    "email": "mario@email.com",
    "password": "12345"
}



###
GET http://127.0.0.1:8000/users/3



###
POST http://127.0.0.1:8000/users/4/measures/
Content-Type: application/json

{
    "height": "168",
    "weight": "60",
    "neck": "70",
    "chest": "70",
    "biceps": "70",
    "waist": "70",
    "thighs": "70",
    "calf": "70"
}




###
POST http://127.0.0.1:8000/users
Content-Type: application/json

{
    "name": "Rebeca Emi Ito",
    "email": "rebecaemiito@email.com",
    "password": "54321"
}



###
POST http://127.0.0.1:8000/users
Content-Type: application/json

{
    "name": "Emi Teste",
    "email": "emiteste1@email.com",
    "password": "321"
}



###
GET http://127.0.0.1:8000/users/3



###
GET http://127.0.0.1:8000/users/3/measures/



### 
DELETE http://127.0.0.1:8000/users/4



###
PUT http://127.0.0.1:8000/users/3
Content-Type: application/json

{
    "name": "Emi Ito",
    "email": "emiito@email.com",
    "birth_date": "2000-09-23T21:32:01.793Z"
}